package ru.asherbakov.enums;

public enum Action {
    CREATE_DOCUMENT,
    DELETE_DOCUMENT,
    CREATE_PERSON_CASE,
    MOVE_TO_ARCHIVE,
    CREATE_DOCUMENT_ERROR,
    DELETE_DOCUMENT_ERROR,
    CREATE_PERSON_CASE_ERROR,
    MOVE_TO_ARCHIVE_ERROR,
    DOWNLOAD_ALL_DOCUMENTS;
}
